language: java
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ModfCg9OS5dKY+Y6nezILdzxJYtIRJ1oEDDeYzkaSalyT0WZP9HaHmRbQ0pyOl2EXIB7ZEmlbgjH0cAAG1f//uV8XQDicDRek30z+vhBqo2D0sCdRC/dqFFN4EP5izs1W3SGIC05WwR38P62oR/QYkO3nR1T7B8gvaXl8mZEt8ThPBaT8cs6LN8sVMSSvo6Wp/xIcrhsF+21dF/VMYoqu8hCBs8P5+CJHdPBsbJwweeTfKif57eCh92XBp5pwir3jQL4XzW2yGGB6paIiLWa3nIrGusZB/xUEAIfBxBspe8JkZz6CpzZsvwWC6WPWyR+Vym2qZV5U5VIoyGWokv28ZELgIC453+TCt/IgnzzA26lkpatSm2CIVawpOTWuIibVHSFCxPBc87nC7U8bird+SwSg28WT1mgmjUx6vD40DaTnyXKAckRTqYlQPB/62eSDQFdP1h3hWZ4xRQ+dpYQPAgbulIsmKqSkUv6RnVvV7XnFr3uUldWT8SZy4+hyTLdc5oIGqPA1ETM0Wnclr3/XEr0hJ9w9QU+SdBrV7nakkugic2JUfdI67lMfOFmHlRw5Q9IIFLq4JpbdLsFqJxwb3heIki6tkc6jX5IeAk5rEkDSVVBgebnUTc9el/4NH3lD38nWmCL5ebECHNXEai5ymzBXrirUm4FT8pz7wH9CCA=
  file: build/libs/nerd-golf-tracker.jar
  on:
    repo: golfholger/nerd-golf-tracker-2
    tags: true
